### ISSUE TITLE
Notice: Your project was added to Compose-Examples

### ISSUE THREAD

**Issue by l4rm4nd** [kaangiray26/forte#101]
Hi @kaangiray26,

many thanks for your contribution to the selfhosting community.

After your last releases I can confirm that reverse proxy support works flawlessly. 

Therefore, I've added your project to my [Compose-Examples ](https://github.com/Haxxnet/Compose-Examples) repository. See your project listed [here](https://github.com/Haxxnet/Compose-Examples/tree/main/examples/forte).

**Comment by kaangiray26** [comment]
Thank you for your kind words!
