### ISSUE TITLE
user info seems missing.

### ISSUE THREAD

**Issue by Leopere** [kaangiray26/forte#118]
https://github.com/kaangiray26/forte/blob/830d58bd120e00761afc8e772f786fc10dc8f815/README.md?plain=1#L147
I'm really excited to try this software but where is this user info given?
![image](https://user-images.githubusercontent.com/1068374/233784869-e3b0fc80-abe4-4f08-a5d6-363ab2e644bb.png)

**Comment by kaangiray26** [comment]
postgres is just the default host set in the `docker-compose.yml`:

```
POSTGRES_HOST: postgres  # Postgres Host/IP
```

I suggest using the discussions section in the repo for things apart from feature requests, bugs and problems.

**Comment by Leopere** [comment]
hmm no I mean user login info.

**Comment by kaangiray26** [comment]
It's written in the documentation:

https://github.com/kaangiray26/forte#Forte-Dashboard

**Comment by Leopere** [comment]
I hate to be a nuisance, in this stage I think there may be a need to update the documentation a touch especially the referenced line at the beginning of this issue.

The other thing is default credentials are a grim way of handling things could it be possible to declare them as an environment variable so that you don't by default give the internet the passwords?  all I can imagine is a botnet targeting these things.
