### ISSUE TITLE
Can't get forte running

### ISSUE THREAD

**Issue by JaxzKyd** [kaangiray26/forte#64]
So this is the docker stack I'm running
```version: '3'
services:
    app:
        image: kaangiray26/forte:1.3
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        environment:
            mode: local
        volumes:
            - C:/Rimatori/Media/Music:/library
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: forte
            POSTGRES_USER: forte
            POSTGRES_PASSWORD: forte
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
```
And on first run the app container gave this in the logs and stopped.
- [Forte - 1st Run.txt](https://github.com/kaangiray26/forte/files/10832518/Forte.-.1st.Run.txt)
Trying to start the container again made the app container give these logs instead then it promptly stopped again
- [Forte - 2nd Run.txt](https://github.com/kaangiray26/forte/files/10832520/Forte.-.2nd.Run.txt)

**Comment by kaangiray26** [comment]
Hi, please make sure you use the latest `docker-compose.yml` file from here:

https://github.com/kaangiray26/forte/blob/main/server/docker-compose.yml

Can you tell me if the problem still occurs?

**Comment by JaxzKyd** [comment]
Used the new compose and edited it
```version: '3'
services:
    app:
        image: kaangiray26/forte:1.3
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local
        volumes:
            - C:/Rimatori/Media/Music:/library
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: forte
            POSTGRES_USER: forte
            POSTGRES_PASSWORD: forte
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data:
```
Still failed, here are the logs for the app and database

- [_forte-app-1_logs.txt](https://github.com/kaangiray26/forte/files/10832543/_forte-app-1_logs.txt)
- [_forte-postgres-1_logs.txt](https://github.com/kaangiray26/forte/files/10832544/_forte-postgres-1_logs.txt)

**Comment by kaangiray26** [comment]
Alright, you might want to take a look at the directory structure for the music library:
https://github.com/kaangiray26/forte/blob/main/README.md#directory-structure-for-the-music-library

**Comment by JaxzKyd** [comment]
Maybe I should read documentation more, I just assumed forte could use a `/Artist/Album/song.flac` directory format. After changing the volume mount to one of the artist folders inside of the directory I got it started.

**Comment by kaangiray26** [comment]
> Maybe I should read documentation more, I just assumed forte could use a `/Artist/Album/song.flac` directory format. After changing the volume mount to one of the artist folders inside of the directory I got it started.

Hey I'm happy to hear it worked in the end.

I can also try to add support for other directory structures. If you want you can create another issue with an example of the directory structure you want in your own library so that I can take a look :)
