### ISSUE TITLE
Cannot add external music library

### ISSUE THREAD

**Issue by jame25** [kaangiray26/forte#70]
My music library is not based in /home, but rather on a sata HDD. Neither of the following folders are accepted (Error: ENOTDIR: not a directory) and Forte quits.

      - /media/plex/media/Music:/library

      - /home/plex/HardDisk/Music:/library ('HardDisk' is a link to /media/plex/media/Music) 

However the following is accepted.

      - /home/plex/Music:/library

Suggestions appreciated.

**Comment by kaangiray26** [comment]
#67

**Comment by kaangiray26** [comment]
Checking on it.

**Comment by kaangiray26** [comment]
Hi again, I've just released a new version, forte-1.7. I've tried using an external drive in the latest release now and didn't encounter any problems. Can you please check if the problem still occurs for you?

**Comment by jame25** [comment]
Hi, running forte-1.8 - I can get the container to run if the 'Music' folder is empty. However as soon as I add some music I get a crash.

Log:
[forte-1.8.log](https://github.com/kaangiray26/forte/files/10854070/forte-1.8.log)

**Comment by kaangiray26** [comment]
Oh I see now, before using the latest version, make sure you remove all previous docker containers, images and volumes.

You can do this so:
* Get the containers using `docker ps -a` and use the `docker rm <container_id>` command to remove containers related to forte.
* Get the images using `docker images` and use the `docker rmi <image_id>` command to remove images related to forte.
* Get the volumes using `docker volume ls` and use the `docker volume rm <volume_name>` command to remove volumes related to forte.

After this try using the latest `docker-compose.yml` file. Let me know if the problem persists.

**Comment by jame25** [comment]
Thanks for the information. I did my best to remove all previous docker containers, images and volumes. Doing so did not make much difference. As a last resort, I deleted the 'forte' database in **postgres** and this appears to have been a necessary step.

I can see forte is now scanning and adding music from the external music library, however there is a crash - log attached.

Log: [forte_new.log](https://github.com/kaangiray26/forte/files/10856813/forte_new.log)

**Comment by kaangiray26** [comment]
I guess you have lots of files and folders in your external drive. I am also using linux and there is a limit for maximum watchers. If that's not sufficient for you, you should increase the number.

You can check your current number with:
```
cat /proc/sys/fs/inotify/max_user_watches
```

It depends on your distro how you should change the value.
You might want to take a look at these articles:
* https://webpack.js.org/configuration/watch/#not-enough-watchers
* https://stackoverflow.com/a/55763478/6561624
* https://stackoverflow.com/questions/65300153/error-enospc-system-limit-for-number-of-file-watchers-reached-angular
* https://itslinuxfoss.com/fix-system-limit-watchers-reached-error/
