### ISSUE TITLE
Different "About" button URL

### ISSUE THREAD

**Issue by JaxzKyd** [kaangiray26/forte#73]
On the artist page the "About" button takes you to a Wikipedia page that it best thinks is the selected artist's Wikipedia page, however this is not always the case
**Page for Bea Miller**
![Bea Miller](https://i.imgur.com/rDxvhxB.png)
**Page the "About" button takes you to**
![Not Bea Miller](https://i.imgur.com/U0fWmrD.png)

Might I suggest this about button changed to take you to the artist's Last.fm or Musicbrainz page? This can also be done for album pages. Navidrome went this route and it has yet to lead me astray

**Comment by kaangiray26** [comment]
Seems like a great suggestion, I'll check on to that.

**Comment by kaangiray26** [comment]
I've used another wikipedia api endpoint that brings better results. I'll try to integrate Last.fm / Musicbrainz as well.
