### ISSUE TITLE
Project Shared Last.fm API Key

### ISSUE THREAD

**Issue by JaxzKyd** [kaangiray26/forte#74]
This is a minor thing, perhaps a API key and secret for Last.fm can be baked into the project with the ability to use your own API key if you so choose?

**Comment by JaxzKyd** [comment]
maybe the same for Genius as well, I'm not sure.

**Comment by kaangiray26** [comment]
I am still thinking about what one might do maliciously with an exposed Last.fm/Genius api key and secret and haven't found anything yet.

I'll add it later once I'm sure of it :)
