### ISSUE TITLE
[Feature request] Signal path UI

### ISSUE THREAD

**Issue by Pheggas** [kaangiray26/forte#81]
Hello. I already made one [feature request](https://github.com/kaangiray26/forte/issues/80)  but I'd like to add another one. 

I noticed [Roon](https://roonlabs.com/) has UI for something like signal traveling / pathing [shown in this picture](https://www.google.com/search?q=roon+sound+preferences&tbm=isch&ved=2ahUKEwi0kJnO_bL9AhXk47sIHaogCfQQ2-cCegQIABAC&oq=roon+sound+preferences&gs_lcp=ChJtb2JpbGUtZ3dzLXdpei1pbWcQAzoECCMQJzoFCAAQgAQ6BwgAEIAEEBM6BwgAEA0QgAQ6BAgAEB46BwgAEIAEEBg6BAgeEAo6BAghEApQ7ARY2Tpghz1oBXAAeACAAcEBiAHxEZIBBDkuMTGYAQCgAQHAAQE&sclient=mobile-gws-wiz-img&ei=wjT7Y7SnBOTH7_UPqsGkoA8&bih=893&biw=461&client=ms-android-nothing&prmd=imvn#imgrc=oqg-q0bI_vYlPM) (and other too as google recommends). I'd like to see this feature in Forte as well. I asked for it Navidrome, Plex and other applications too but everyone just ignored it. However I see Forte as very strong competitor in selfhosted music streaming branch. 

Good luck!

**Comment by kaangiray26** [comment]
Hey, I think I can add something like a source audio display that shows the audio format, quality etc.

**Comment by Pheggas** [comment]
Yeah that would be awesome. Maybe with some fancy icons under certain conditions like Hi-Res lossless audio etc. Maybe I could do design draft? (I'm not a designer but I would do my best)

**Comment by kaangiray26** [comment]
I think I can read the incoming audio source to check out its format, bitrate etc. I also use forte on my own with a library only with FLAC files :laughing: 

For the icons I like to mainly [Bootstrap Icons](https://icons.getbootstrap.com/) mainly. I have found these possible icons:
- [High Definition Audio](https://icons.getbootstrap.com/icons/badge-hd-fill/)
- [Standard Definition Audio](https://icons.getbootstrap.com/icons/badge-sd-fill/)

But I am open to new designs as well, I like bootstrap icons because I can just use the icons using CSS classes, if you can come up with a nice design that I can just use via a stylesheet I'd be happy to consider adding it.

Thank you!

**Comment by Pheggas** [comment]
I did a little research and i could do a .svg but i'm not aware of any way to convert it to html like this
```<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-badge-hd-fill" viewBox="0 0 16 16">
  <path d="M10.53 5.968h-.843v4.06h.843c1.117 0 1.622-.667 1.622-2.02 0-1.354-.51-2.04-1.622-2.04z"/>
  <path d="M2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2zm5.396 3.001V11H6.209V8.43H3.687V11H2.5V5.001h1.187v2.44h2.522V5h1.187zM8.5 11V5.001h2.188c1.824 0 2.685 1.09 2.685 2.984C13.373 9.893 12.5 11 10.69 11H8.5z"/>
</svg>```

**Comment by Pheggas** [comment]
I never took a look into .svg files but now i did and i realised the code i shared here is stadard in all SVG files. This way i can create some simple SVG in something like Adobe Illustrator share it to you. I'll let you know when i will have it done.

**Comment by kaangiray26** [comment]
I can now successfully retrieve the bitrate for the file. What do you think about the audio quality ranges?
Should I just label audio files <= 320 kbps as standard quality and audio files with > 320 kbps as high quality?

**Comment by Pheggas** [comment]
I would so <=128 kbps as LQ, 128>=320<= as SQ, 320>=<=1500 kbps as HQ, and 1500> as Hi-Res which i will design an icon for.

**Comment by kaangiray26** [comment]
I see, for the design btw a HTML button with a LQ/SQ/HQ text would also suffice I think

**Comment by Pheggas** [comment]
As you can now read the bitrate, you could maybe show the exact bitrate that's on that song?

**Comment by kaangiray26** [comment]
I've added a feature to show the quality under the desktop player track title and if you click the quality indicator a modal will pop up showing various information about the audio data.

**Comment by kaangiray26** [comment]
I'll close the issue if this suffices for you.

**Comment by Pheggas** [comment]
I'll give it a spin and see. But till then i will close the issue as it's been added. Thank you.
