### ISSUE TITLE
App crashes when encounters file

### ISSUE THREAD

**Issue by obsidiangroup** [kaangiray26/forte#85]
When starting the server, the app crashes if it encounters a file where it expects a directory:

> pp_1       | Watching for changes...
app_1       |     Adding folder 1/46...
app_1       | node:fs:1438
app_1       |   handleErrorFromBinding(ctx);
app_1       |   ^
app_1       | 
app_1       | Error: ENOTDIR: not a directory, scandir '/library/2019.mp3'
app_1       |     at Object.readdirSync (node:fs:1438:3)
app_1       |     at get_tags (file:///js/db.js:257:20)
app_1       |     at walk_folders (file:///js/db.js:237:26)
app_1       |     at file:///js/db.js:157:23
app_1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
app_1       |   errno: -20,
app_1       |   syscall: 'scandir',
app_1       |   code: 'ENOTDIR',
app_1       |   path: '/library/2019.mp3'
app_1       | }
app_1       | 
app_1       | Node.js v19.7.0

As you can see, this is on first run.  App should not crash in these situations, but rather ignore the file and continue.

**Comment by obsidiangroup** [comment]
1.8 gets closer, but

>app_1       | => Added album: The Man and His Music
app_1       | => Added album: Eminem - Kamikaze (2018) [320]
app_1       | => Updated cover for the artist: Korn
app_1       | => Updated cover for the artist: T I
app_1       | file:///node_modules/music-metadata/lib/ParserFactory.js:71
app_1       |                     throw new Error('Guessed MIME-type not supported: ' + guessedType.mime);
app_1       |                           ^
app_1       | 
app_1       | Error: Guessed MIME-type not supported: application/xml
app_1       |     at ParserFactory.parse (file:///node_modules/music-metadata/lib/ParserFactory.js:71:27)
app_1       |     at async parseFile (file:///node_modules/music-metadata/lib/index.js:39:16)
app_1       |     at async get_metadata (file:///js/db.js:698:20)
app_1       |     at async handle_album (file:///js/db.js:641:20)
app_1       | 
app_1       | Node.js v19.7.0
server_app_1 exited with code 1

**Comment by kaangiray26** [comment]
forte-1.9 brings some changes to metadata retrieveal and supported extensions. Maybe the latest version (forte-2.0) solves it for you?
