### ISSUE TITLE
Go off embedded tags for albums instead of folder name

### ISSUE THREAD

**Issue by JaxzKyd** [kaangiray26/forte#89]
So after starting up forte again with my entire library this time, I noticed a few things... For the record this is how my library is structured
```
/library/
└── artist name/
   ├── [year] album name (album type)/
   |   ├── 01 - Title.flac
   |   ├── 02 - Title.flac
   |   ...
   |   └── cover.jpg # occasionally there isn't a cover.jpg file and the covers are embedded, but that's a whole different thing
   |
```
Here is an example from my library
```
/library/
└── Bea Miller/
   ├── [2018] aurora (Album)/
   |  ├── 01 - song like you.flac
   |  ├── 02 - burning bridges.flac
   |  ├── 03 - motherlove.flac
   |  ├── 04 - i can't breathe.flac
   |  ├── 05 - like that.flac
   |  ├── 06 - buy me diamonds.flac
   |  ├── 07 - outside.flac
   |  ├── 08 - girlfriend.flac
   |  ├── 09 - bored.flac
   |  ├── 10 - warmer.flac
   |  ├── 11 - repercussions.flac
   |  ├── 12 - S.L.U.T..flac
   |  ├── 13 - crash&burn.flac
   |  ├── 14 - to the grave.flac
   |  └── cover.jpg
   ├── [2019] feel something (Single)/
   |  ├── 01 - feel something.flac
   |  └── cover.jpg
   ├── [2020] elated! (Album)/
   |  ├── 01 - hallelujah.flac
   |  ├── 02 - FEEL SOMETHING DIFFERENT.flac
   |  ├── 03 - forever is a lie.flac
   |  ├── 04 - making bad decisions.flac
   |  ├── 05 - i never wanna die.flac
   |  ├── 06 - wisdom teeth.flac
   |  ├── 07 - self crucify.flac
   |  └── cover.jpg
   ├── [2023] lonely bitch (Single)/
   |  ├── 01 - lonely bitch.flac
   |  └── cover.jpg
   |
```
I think this is a cause of a few issues in my forte instance, here are some login credentials for it
`Server:https://forte.rimatori.com`
`Username:Kaan`
`Token:a8347f83092f6a0fe726734ee14274ab`
Now on that server, every album folder follows that above structure EXCEPT a few here in there, most notably, 
K-12 (After School - Deluxe Edition)
Cry Baby (Deluxe Edition)
Now these albums are just in a `/artist/album name` instead of the `/artist/[year] album name (album type)` like the rest of my library.
As you can see for yourself, they are the only albums with album art and playable tracks, the rest of the albums just show up like this
![image](https://user-images.githubusercontent.com/39567321/222003699-93556b8a-2bed-4b13-9053-dc49f5c820ed.png)
![image](https://user-images.githubusercontent.com/39567321/222003988-f80b8363-8e73-486e-bb39-d3b9edbca305.png)
I don't know, I assume it's because it's building albums based on folder names and not tags?

**Comment by kaangiray26** [comment]
Which version is this btw?

**Comment by JaxzKyd** [comment]
You update really fast haha 😅
I believe I built the images right after you made this commit [8d88b9c](https://github.com/kaangiray26/forte/commit/8d88b9c6789968dc26ec334397db02fefa758b1b)

**Comment by kaangiray26** [comment]
I can't seem to reproduce the problem myself in my own library. Can you maybe send me one of your problematic album folders as a zip in private so that I can try it in my own machine?

**Comment by JaxzKyd** [comment]
Not a problem, uploading it to mega now and I'll send you the link in an email

**Comment by kaangiray26** [comment]
Great, thanks so much!

**Comment by JaxzKyd** [comment]
Sent out the email 👍

**Comment by kaangiray26** [comment]
This commit should solve the problem for good.

**Comment by JaxzKyd** [comment]
We're back in business 🎉
