### ISSUE TITLE
App not properly routing

### ISSUE THREAD

**Issue by obsidiangroup** [kaangiray26/forte#90]
App routing doesn't seem to properly work.

If you go to http://<your_ip>:3000/login or http://<your_ip>:3000/dashboard, you receive the error:
`{"error":"not found"}`

However, if you point your browser initially at http://<your_ip>:3000, the app will route you to /login and display the login page.

This happens even after you are logged in.  If you attempt to refresh the page, this happens as well.  Experienced the problem in 1.4, onward (including 2.0).

**Comment by kaangiray26** [comment]
Strange, the problem doesn't occur to me.

If I'm using forte locally, I always use the address `http://localhost:3000`. Following routes all work for me even if I manually type each one of them:
* http://localhost:3000/
* http://localhost:3000/dashboard
* http://localhost:3000/login

Which browser do you use? Are you on mobile?

**Comment by kaangiray26** [comment]
I believe the latest release solves the problem.
