### ISSUE TITLE
log_in is not defined

### ISSUE THREAD

**Issue by Silur** [kaangiray26/forte#95]
Using the docker image (e6cb9e7ba889), after changing the default password on the dashboard, any login attempt results in:
```
Uncaught ReferenceError: log_in is not defined
    onclick <forte instance>/login:1
```

The button onclick event simply doesn't exist

**Comment by RazorSh4rk** [comment]
skill issue

**Comment by Silur** [comment]
manually calling the focus method https://github.com/kaangiray26/forte/blob/70a14f7bb7b7bc74c2bcd1b0f9cf6f813c1b402e/server/dashboard/src/components/Login.vue#L53 for password checking will pass trough copy-paste and password managers too
